# Check Insights/"Dependency graph" to make sure there are no errors in this file.
version: 2
updates:
    # Non-Python ecosystems which may also be of interest are Docker,
    # git submodules, and Terraform.
    - package-ecosystem: "pip"
      directory: "/"
      schedule:
        interval: "weekly"
        day: "friday"
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
        interval: "weekly"
        day: "friday"
