name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: "test w/ Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
    - uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - run: python -m pip install --upgrade pip
    - run: python -m pip install nox
    - run: nox --session test-${{ matrix.python-version }}

  lint:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.8"

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('.pre-commit-config.yaml') }}-${{ hashFiles('pyproject.toml') }}
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PYTHON_VERSION }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - run: python -m pip install --upgrade pip
    - run: python -m pip install nox
    - run: nox --session lint
    - run: echo "::warning file=pkg/__init__.py,line=2,::Line-only message"
    - run: echo "::warning file=pkg/__init__.py,line=3,col=16::column 16 message"
