name: Release
on:
  pull_request:
    types: ["closed"]
    branches: ["master"]

jobs:
  prep:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged

    steps:
    - uses: actions/checkout@v2
    - name: Set up git user
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
    - uses: actions/setup-python@v1
      with:
        python-version: "3.8"
    - run: python -m pip install --upgrade pip
    - run: python -m pip install httpx nox packaging tomlkit
    - run: nox --session release

  build:
    needs: [prep]
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: "3.8"
    - run: python -m pip install --upgrade pip
    - run: python -m pip install poetry
    - run: poetry build
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist
